# Generated by Django 3.1.5 on 2021-04-28 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_yazilarmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('isim_soyisim', models.CharField(max_length=50)),
                ('mesaj', models.TextField()),
                ('gonderme_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Iletisim',
            },
        ),
        migrations.CreateModel(
            name='YorumlarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField()),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('duzenleme_tarihi', models.DateTimeField(auto_now=True)),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to=settings.AUTH_USER_MODEL)),
                ('yazi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorum', to='blog.yazilarmodel')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'db_table': 'Yorumlar',
            },
        ),
        migrations.CreateModel(
            name='BegenilerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begeni', to=settings.AUTH_USER_MODEL)),
                ('yazi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begeniler', to='blog.yazilarmodel')),
            ],
            options={
                'verbose_name': 'Begeni',
                'verbose_name_plural': 'Begeniler',
                'db_table': 'Begeniler',
            },
        ),
    ]
