# Generated by Django 3.1.5 on 2021-04-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_begenilermodel_iletisimmodel_yorumlarmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazilarmodel',
            old_name='resmi',
            new_name='resim',
        ),
    ]
