# Generated by Django 3.1.5 on 2021-04-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210429_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BegenilerModel',
        ),
    ]
